
- name: Create folder directory for inputs configuration
  file:
    path: "{{ item }}"
    state: directory
    owner: splunk
    group: splunk
    recurse: yes
  with_items:
    - /opt/splunk/etc/apps/inputs_app/local/

- name: copy inputs.conf
  copy:
    src: inputs.conf
    dest: /opt/splunk/etc/apps/inputs_app/local/inputs.conf
    owner: splunk
    group: splunk
  notify: restart splunk
