
- name: Create folder directory for web configuration
  file:
    path: "{{ item }}"
    state: directory
    owner: splunk
    group: splunk
    recurse: yes
  with_items:
    - /opt/splunk/etc/apps/web_app/local/

- name: copy web.conf to splunk server
  copy:
    src: web.conf
    dest: /opt/splunk/etc/apps/web_app/local/web.conf
    owner: splunk
    group: splunk
  notify: restart splunk
