---

- name: copy serverclass.conf to splunk server
  copy:
    src: serverclass.conf
    dest: /opt/splunk/etc/system/local/serverclass.conf
    owner: splunk
    group: splunk
  notify: restart splunk
