- name: check if BOTSv3 app exists
  stat:
    path: /opt/splunk/etc/apps/botsv3_data_set
  register: botsv3_app

- name: download BOTSv3 dataset
  unarchive:
    src: 'https://botsdataset.s3.amazonaws.com/botsv3/botsv3_data_set.tgz'
    dest: /opt/splunk/etc/apps 
    owner: splunk
    group: splunk
    remote_src: yes
  when: botsv3_app.stat.exists == False
