- name: Check if SSE App exists
  stat:
    path: /opt/splunk/etc/apps/Splunk_Security_Essentials
  register: sse_app

- name: download ESCU app from S3 bucket
  get_url:
    url: '{{ s3_bucket_url }}/{{ splunk_security_essentials_app }}'
    dest: /tmp/sse_app.tgz
  when: sse_app.stat.exists == False

- name: Install sse app via REST
  uri:
    url: "https://127.0.0.1:8089/services/apps/local"
    method: POST
    user: "admin"
    password: "{{ splunk_admin_password }}"
    validate_certs: false
    body: "name=/tmp/sse_app.tgz&update=true&filename=true"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: [ 200, 201 ]
    timeout: 30
  when: sse_app.stat.exists == False
  notify: restart splunk
