---
# splunk search_head
splunk_admin_password: changeme
splunk_url: https://download.splunk.com/products/splunk/releases/8.1.0.1/linux/splunk-8.1.0.1-24fd52428b5a-Linux-x86_64.tgz
splunk_binary: splunk-8.1.0.1-24fd52428b5a-Linux-x86_64.tgz
